In [2]:
import numpy as np

In [3]:
def ex6(arr):
    arr[arr != 0] = -1
    return arr
a = np.array([int(i) for i in input(": ").split()])
print(ex6(a))

: 3 325 2 5 2 52 52 3 -1
[-1 -1 -1 -1 -1 -1 -1 -1 -1]


In [4]:
def ex2(n):
    arr = np.zeros((n,n), dtype=int)
    arr[1::2,::2] = 1
    arr[::2,1::2] = 1
    return arr
print(ex2(5))

[[0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]]


In [82]:
def ex2(n):
    return np.tile(np.array([[1,0],[0,1]]), (n,n))
print(ex2(5))

[[1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]]


In [6]:
def ex5(n):
    arr = np.zeros((n,n), dtype=int)
    arr[0::2,::2] = 1
    arr[::2,1::2] = 1
    return arr
print(ex5(9))

[[1 1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1 1]]


In [7]:
def ex12(n):
    arr = np.ones((n,n))
    arr[0]=0
    arr[-1]=0
    arr[:,0]=0
    arr[:,-1]=0
    return arr
print(ex12(4))

[[0. 0. 0. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 0. 0. 0.]]


In [8]:
def ex11(n):
    arr = np.ones((n+2,n+2), dtype=int)
    arr[0]=0
    arr[-1]=0
    arr[:,0]=0
    arr[:,-1]=0
    return arr
print(ex11(8))

[[0 0 0 0 0 0 0 0 0 0]
 [0 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 0]
 [0 0 0 0 0 0 0 0 0 0]]


In [9]:
def ex14():
    return np.tile(np.array([[0,1],[1,0]]), (4,4))
print(ex14())

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [10]:
def ex13(n):
    return np.unravel_index(n, (4,5,6))
print("In the matrix of 70-th element index is", ex13(70))

In the matrix of 70-th element index is (2, 1, 4)


In [44]:
def ex16(n):
    arr = np.zeros((n,n), dtype=int)
    arr[::1,::2] = 1
    return arr
print(ex16(9))

[[1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1]]


In [66]:
def ex17(n):
    arr = np.arange(0,n+1)
    arr[(arr > n/2) ^ (arr < (3*n)/4)] *= 0
    return arr
print(ex17(10))

[0 0 0 0 0 0 6 7 0 0 0]


In [72]:
def ex20(n):
    arr = np.linspace(0,1,n)[1:-1]
    return arr
print(ex20(10))

[0.11111111 0.22222222 0.33333333 0.44444444 0.55555556 0.66666667
 0.77777778 0.88888889]


In [74]:
def solve_by_cramer(mA, b):
    n = mA.shape[0]
    det = np.linalg.det(mA)
    xs = np.empty(n)
    if det == 0:
        return None
    for i in range(n):
        mAi = np.copy(mA)
        mAi[:, i] = b
        xs[i] = np.linalg.det(mAi) / det
    return xs

a = np.array([[1,2,3,-2],[1,-1,-2,-3],[3,2,-1,2],[2,-3,2,1]])
b = np.array([6,8,4,-8])
roots = solve_by_cramer(a, b)
print(roots)
print(np.linalg.solve(a,b))
ax = np.dot(a,roots)
print(ax)
print(np.allclose(ax, b))

[ 1.125   1.9375 -1.125  -2.1875]
[ 1.125   1.9375 -1.125  -2.1875]
[ 6.  8.  4. -8.]
True


In [75]:
def calc(mA, mB):
    res = (mA*3)-(mB@(mA-mB*2))
    return res

a = np.array([[4,5,-2],[3,-1,0],[4,2,7]])
b = np.array([[2,1,-1],[0,1,3],[5,7,3]])
print(calc(a,b))

[[ 3  0  1]
 [24 36  3]
 [ 9 48 60]]


In [76]:
def solve_by_inv(mA, mB):
    if np.linalg.det(mA) == 0:
        return None
    xs = np.linalg.inv(mA) @ mB
    return xs

a = np.array([[-1,2,0],[-3,2,1],[1,2,3]])
b = np.array([[5,-1,3],[4,2,1],[-1,0,2]])
roots = solve_by_inv(a,b)
print(roots)
print(np.linalg.solve(a,b))
prod = a @ roots
print(prod)
print(np.allclose(prod,b))

[[-0.375  -1.      0.625 ]
 [ 2.3125 -1.      1.8125]
 [-1.75    1.     -0.75  ]]
[[-0.375  -1.      0.625 ]
 [ 2.3125 -1.      1.8125]
 [-1.75    1.     -0.75  ]]
[[ 5.00000000e+00 -1.00000000e+00  3.00000000e+00]
 [ 4.00000000e+00  2.00000000e+00  1.00000000e+00]
 [-1.00000000e+00 -2.22044605e-16  2.00000000e+00]]
True
